<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Items\" />
    <Folder Include="Scripts\Bullet\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="README.md" />
    <Content Include="Scripts\Items\ITEMS.md" />
    <Content Include="Scripts\Player\Inventory\INVENTORY.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Quinquennium.csproj" />
  </ItemGroup>
</Project>